<?php  ?>
<h3>Elõzmények</h3>
<p>Erdõmérnökök, pedagógusok és más szakemberek baráti csoportja, mintegy 1990 óta  szervez környezetvédelmi akciókat, környezeti nevelési programokat. Korábban ezek a rendezvények, többnyire valamelyik közművelõdési intézmény hátterével valósultak meg, mégis a szervezők azonosságából adódóan egységes szemlélet és célrendszer mentén kapcsolódtak össze. A természetismereti túrákat, kirándulásokat, vetélkedõket, erdei iskolai programokat és nyári természetvédelmi táborokat környezetvédelmi akciókat, természetvédelmi kutató és feltáró munkát szervezõ és lebonyolító szakértõi „stáb” 1997-ben létrehozta a Kerekerdõ Alapítványt, mely 1998 jan. 1-től közhasznú szervezet. Az Alapítvány 10 éve folyamatosan működik, 2002 óta saját központot működtet Szombathely belvárosában, mely azon túl, hogy a szervező munka helyszíne, környezeti nevelési, és kulturális programoknak ad helyet, illetve környezeti tanácsadó irodaként is működik.</p>

<h3>Az alapítvány céljai</h3>
<p>Az alapító okiratban megfogalmazott egy-mondatos összefoglaló cél „a természet és az emberi környezet védelme és a környezeti kultúra fejlesztése” jelzi, hogy a szűkebben értelmezett környezet és természetvédelmi problémákkal való foglalkozáson kívül a környezeti nevelés, kiemelt feladata az alapítványnak. Az alapítvány célja a természetes biológiai sokféleség megõrzése, a természeti erõforrásokkal való gazdálkodásban a tartamosság, és a fenntartható fejlõdés elveinek érvényesítése. Támogatja a környezeti problémákkal kapcsolatos információáramlás fejlesztését, a nyilvánosság megteremtését, a témával foglalkozó intézmények, szervezetek és személyek együttműködését.</p>

<h3>Az alapítvány működése</h3>
<p>Az alapítvány a kuratórium által jóváhagyott éves munkaterv alapján működik, mely meghatározza a legfontosabb törekvéseket, programokat és szolgáltatásokat. A törekvések az alapítvány kapcsolatainak építését, infrastruktúrájának fejlesztését, a forrásteremtéssel kapcsolatos munkánkat jelenti. A programok az alapítvány által szervezett és megvalósított, konkrét helyen és meghatározott célcsoportnak szóló tevékenységek. A szolgáltatások kiajánlott lehetőségek, melyek külső igény, megrendelés alapján realizálódnak.   Legfontosabb programjaink a környezeti nevelés, a természetvédelem, a környezetvédelem, és a társadalmi részvétel, civil együttműködés témaköreihez kapcsolódnak.  Az alapítvány együttműködésre törekszik minden olyan intézménnyel és szervezettel, mely hasonló tevékenységet végez. Működésünk fontos alapelve a nyilvánosság.</p>

<h3>A szervezet kapacitásai</h3>
<p>Az alapítvány programjainak lebonyolítását 15-20 fős stáb végzi rendszeresen. Emellett kb. 20 fős azon önkéntesek száma, akik egyes megmozdulások, demonstrációk idején munkánkat segítik. Jelenleg az alapítvány Szombathely belvárosában önálló központot  tart fenn  (ÖKOCELLA), állandó, heti 30 órás nyitva tartással. A  központ, mint civil intézmény környezeti tanácsadó irodaként és zöld kultúrházként, oktatóközpontként is működik. A segítséget, információt kérők ide térhetnek be, illetve ez az iroda ad helyet számos programnak, kiállításnak is. Felszereltségünk lehetővé teszi, akár 40 főnek szervezett előadás, tanfolyam megrendezését kiállítások megvalósítását. Az ÖKOCELLA évek óta helyszíne rendhagyó iskolai és óvodai foglalkozásoknak. Egy osztálynyi gyerekkel kényelmesen tudunk foglalkozni. Ugyanitt környezet- és természetvédelmi, és környezeti neveléssel kapcsolatos könyvek, kiadványok vásárolhatók, kölcsönözhetők, vagy a betérők az olvasósarokban helyszínen is tájékozódhatnak az őket érdeklő témákról. Az alapítványnál 4 fő diplomás munkatárs dolgozik főállásban.  Forrásteremtő munkánk több lábon áll. Bevételeink harmada  saját programjaink részvételi díjaiból származik. Jelentős tétel még a pályázatokból nyert összeg, de szponzorokat is gyűjtünk. A utóbbi 5-6 évben   évben, évi 8-10 millió Ft-ot mozdítottunk meg a környezet- és természetvédelem ügyéért. 2005-ben több mint 20 millió Ft-t fordítottunk céljaink megvalósítására.</p>


<h3>Legfontosabb elért eredményeink</h3>
<p>Alapítványunk a helyi, illetve a regionális életben felvállalt széles körű környezet-, és természetvédelmi tevékenységének köszönhetően egyre ismertebbé vált. Környezeti nevelési programjainkon egy év alatt szerény számítások szerint is mintegy 1000 fő, többségében gyerek vesz részt. Egyre nő azon felkérések száma, melyek erdei iskolai programok versenyek megrendezésére, szervezésére irányulnak. Közreműködtünk az Őrségi Nemzeti Park létrehozásában, a tudományos előkészítő munkában éppúgy, mint a lobbitevékenységben és a lakossági felvilágosító munkában. Több megyei illetve regionális tervezési, és döntés előkészítő folyamatban vettünk részt véleményezéssel, állásfoglalással. Számos alkalommal léptünk hivatalos kapcsolatba a környezetvédelmi, ill. a természetvédelmi hatósággal, hivatalos eljárást kérve több ügyben. Aktív részvétellel segítettünk az elmúlt fél évszázad legfenyegetőbb környezetvédelmi ügyévé vált toronyi lignitbánya és hőerőmű elleni kampányt. Ennek során több mint tízezer aláírást gyűjtöttünk.  Az alapítvány két könyvsorozatot is útnak indított. Az „Encián könyvek” a környezeti nevelési módszerek, információk terjesztését szolgálja,  ennek keretében a „Természetről a természetben” c környezeti nevelési módszertani kiadványunk jelent meg. A „Ciklámen füzetek” a környezet- és természetvédelemmel kapcsolatos tudományos és tényfeltáró munkáknak ad teret. Ez utóbbiból a Vas-hegy és a Pinka-mente természeti és kultúrtörténeti értékei címmel jelent meg a legújabb kiadványunk Negyedéves tájékoztató hírlevelünk a „Kabóca”, alkalmanként ezerkétszáz családhoz jut el. A Környezet- és természetvédő társadalmi szervezetek XIII. országos találkozóját a Magyar Természetvédők Szövetségével, 2003. márciusában mi rendeztük Szombathelyen. Ezen közel 900 résztvevő volt. Központunkat az  ÖKOCELLÁT, mely egy civil környezet és természetvédelmi intézmény, (tanácsadó iroda, információs pont, oktatási és képzési központ, kiállító tér, stb.) 2002-ben hoztuk létre. Azóta sikerült berendezni saját képünkre formálni. Tíz éve aktívan részt veszünk a zöld szervezetek regionális és országos együttműködési fórumain, Öt éve a Kerekerdő Alapítvány országos szinten vezető szerepet tölt be az erdők ügyében folytatott szakmapolitikai és érdekérvényesítő  munkában.</p>


<h3>Az alapítvány élõ programjai</h3>

<p><strong>Környezeti nevelés:</strong> Az alapítvány legjelentõsebb tevékenysége. Természet centrikus programjainkat a „Természetrõl a természetben” c. programblokk tartalmazza. Ide tartoznak a természetismereti túrák (az elmúlt tanévben havonta 2-3 volt), a többnapos, autóbuszos, természetvédelmi kirándulások, az erdei iskolai hétvégék (évszakonként egy, tanévente négy), a terepgyakorlatok, a vetélkedõk, a nyári természetvédelmi táborok (évek óta nyaranta hat - hét egy hetes tábort szerveztünk), A Kámoni Arborétumban működtetjük az Ökosulit és egy városszéli óvodában „Erdei ovi” programot csinálunk.  Bázisiskolai programunk keretében számos alkalommal segítettük tanácsadással és személyes közreműködéssel iskolák kirándulásait, erdei iskoláit, vetélkedõit, és pályázatait. Ezen kívül továbbképzéseken (Gayer Gyula Szabad-egyetem) és kiadványok terjesztésével és kiadásával  népszerűsítjük a műfajt. Az ÖKOCELLA ad teret a tanévben megvalósított környezetvédelmi foglalkozás sorozatainknak, rendhagyó tanóráinknak. A hulladékokkal (Kukalógia), a háztartással (Zöld-őr-szem, Kamratanoda)), az energiával (Energia őrjárat), kapcsolatos sorozatainkon évente 40-50 csoport (1000-1200 gyerek fordul meg)</p>

<p><strong>Természet és kultúra:</strong> A kerekerdő Alapítvány sajátos tevékenysége olyan kulturális rendezvények megvalósítása, melyekben ötvöződnek a humán és természettudományok sajátosságai. Évente több un. nagyrendezvényz is megvalósítunk, melyeken több száz a résztvevők száma. Októberben a Múzeumfaluban az Állatok világnapja alkalmából két napos programot szoktunk szervezni, tavasszal pedig a Madarak és fák napjához kötődően a Kámoni Arborétumban egy zenés rendezvényre várjuk a város polgárait. Ez utóbbiból egy kulturális sorozat szerveződik éppen (Cum musica pro silva).  Az Őszi és téli hónapokra időzített jellegzetes programjaink azok a kulturáluis est sorozatok, melyek egy-egy ország (A kerek világ kicsiben), vagy magyar táj (Maroknyi Magyarország) természeti és kulturális értékeit mutatjuk be. Minden esthez kötődik kiállítás, több előadás, zenés és iodalmi program és ételkostoló.  Ezek teltházas rendezvények. Évente általában négy ilyen estet szervezünk.  (Pl.: Lengyel est, Portugál est, Rábaközi est, Őrségi est, stb.). Az Ökocella több színvonala természet fotókiállításnak is helyszíne volt.</p>

<p><strong>Természetvédelem:</strong> A Vas-hegy program célja a terület természetvédelmi értékeinek feltárása és helyi védettségének előkészítése Ez ügyben neves szakembereket nyertünk meg, akik kutató, felmérõ munkájuk eredményeit egy átfogó tanulmányban összegezték, melynek kiadása 2004. áprilisában megtörtént. A térségről egy gazdag fotó kiállítási anyagot állítottunk össze. A következő lépés a helyi önkormányzatokkal együttműködve a védetté nyilvánítás előkészítése, megvalósítása. 2007-ben sikerült megjelentetni a tanulmánykötet  színes ismeretterjesztő változatát. Részt veszünk a térségben alakuló naturpark előkészítésében. Az Őrség program is több éves munkát takar. Részt vettünk az Őrségi Nemzeti Park létrehozását szorgalmazó lobbi tevékenységben, sajtómunkával segítettük a nemzeti parkkal kapcsolatos kételyek, ellenérzések, félreértések eloszlatását. A nemzeti parkot előkészítő tudományos előkészítő munkában is közreműködtünk, az összefoglaló tanulmányt egy történeti ökológiai fejezettel gazdagítottuk. Ismeretterjesztő kiadványokat, készítettünk, előadásokat tartottunk. Fizikai munkánkkal, (szénagyűjtés, adventív fajok irtása) már tizenkhat éve, a fokozottan védett szőcei láprét természetvédelmi kezeléséhez is hozzájárulunk. Lépéseket tettünk a Kámoni Arborétum ismeretterjesztõ funkcióinak fejlesztésére, állapotának javítására Részt veszünk a Natura 2000-hálózat bemutató, tájékoztató munkájában. A Rába program keretében a készülő folyógazdálkodási tervhez az ökológiai szempontok erősítésével egy több száz oldalas tanulmány készítésével járultunk hozzá fotókiállítást állítottunk össze, melyet több helyszínen mutattunk be. Az ERDŐ program mintegy öt éve létezik, országos, regionális és helyi elemekkel. A zöld szervezetek országos találkozóhoz igazodva többnapos  Országos erdőfórumot, illetve szekcióülést szakmai műhelynapot szerveztünk, kezdeményezésünkre jött létre az erdészeti és a zöld szervezetek részvételével működő  érdekegyeztető fórum, több országos döntéselőkészítő folyamatban vettünk részt eredményesen.</p>

<p><strong>Környezetvédelem:</strong> Korábban más, főleg környezeti nevelési programjainkhoz kötődően több szűkebben vett környezetvédelmi tevékenység is szerepet kapott (előadások, szemétgyűjtő akciók, stb.) Figyelemmel kísérjük a városban működő szelektív hulladékgyűjtést,  részt vettünk a toronyi lignibánya elleni kampányban, számos utcai akciót szerveztünk, a klímaváltozás, a fosszilis energiahordozók használata, a génmanipulált termékek használat és termesztése ellen. Részt vettünk az agrárkörnyezet-gazdálkodási program, illetve a biotermékek népszerűsítésében fórumok, akciók szervezésével és kiadványok terjesztésével. E tevékenységünk országos és nemzetközi kampányokhoz kapcsolódnak. Szombathely belvárosában működtetett irodánk (ÖKOCELLA), napi 6 órás nyitva tartással környezeti tanácsadással, információ szolgáltatással, kiadványok terjesztésével, rendezvények szervezésével, zöld érdekérvényesítéssel, esetek ügyek felgöngyölítésével  foglalkozik. Tanácsadó irodánkhoz évente 500-600 megkeresés érkezik, melyeket ingyenes szolgáltatás keretében kezelünk, olykor hatósági eljárások kezdeményezésével, államigazgatási eljárásokban való részvétellel. .</p>

<p>Társadalmi részvétel, együttműködés: Aktívan részt veszünk a Nyugat-dunántúli Regionális Környezetvédelmi Fórum munkájában, igyekszünk összefogni Vas megye zöld civil szervezeteit. A természetvédelem – erdőgazdálkodás és egyes környezeti nevelési témákban országos feladatokat vállalunk fel a témával foglalkozó civil és hivatalos körök közti párbeszéd érdekében. A Környezet- és természetvédő társadalmi szervezetek XIII. országos találkozóját a Magyar Természetvédők Szövetségével, 2003. Márciusában mi rendeztük Szombathelyen. Ezen közel 900 résztvevő volt. Képviselőink, szakértőink útján igyekszünk figyelemmel kísérni és kontrollálni a városi megyei és regionális döntési szintek munkáját. A regionális és országos döntéselőkészítő,  folyamatokban rendszeresen részt veszünk. Különösen az erdőkkel kapcsolatos érdekképviseleti és érdekérvényesítő munkánk vált jelentőssé. E témában országos erdészeti és zöld szervezetekkel, valamint önkormányzatokkal is együtt működünk.</p>



